name: Haiku Reusable Workflow - Deploy To Azure App Service

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
        default: ubuntu-latest
      artifact-to-deploy:
        required: true
        type: string
      env-name:
        required: true
        type: string
      env-url:
        required: true
        type: string
      app-name:
        required: true
        type: string
  

jobs:
  deploy-to-azure-app-service:

    
    name: Deploy to ${{ inputs.env-name }}
    
    runs-on: ${{ inputs.runs-on }}
    
    environment: 
      name: ${{ inputs.env-name }}
      url: ${{ inputs.env-url }}
    
    steps:

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        # Artifact name
        name: ${{ inputs.artifact-to-deploy }}
        # Destination path
        path: ${{ inputs.artifact-to-deploy }}
        
    - name: 'Login via Azure OIDC'
      uses: azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2.2.10
      with: 
        app-name: ${{ inputs.app-name }}
        package: ${{ inputs.artifact-to-deploy }}
